### ISSUE TITLE
Restbox shutdown

### ISSUE THREAD

**Issue by Halama** [keboola/restbox-bundle#3]
Restbox by při spuštění jobu měl vyhodit user error a říct že jeho podpora byla ukončena a byl vypnut.
Chybu by to mělo začít vyhazovat v pondělí 12. listopadu 2018.

https://www.timeanddate.com/countdown/launch?iso=20181112T09&p0=204&msg=RestBox+Final+Countdown&font=cursive

**Comment by ErikZigo** [comment]
Nasazeno https://github.com/keboola/restbox-bundle/pull/4
